var a = 123;
var b;

func main(args)
{
	var c;
	
	if a {
		return;
	}
	else if a + 2 > 23
	{
		return "sdf";
	}
	else
	{
		return 2;
	}
	
	var anon = func oops(n) {
		println("Hello from anon function: ", n);	
	};
	anon(1337);
	
	b = "a " + args[1];
	
	var sometable;
	sometable.a = 123;
	sometable:println("help");
	sometable:len();
	
	var i = 10;
	while i-- {
		println("i: ", i);
	}
	
	return false;
}